### PR TITLE
Group by NCPO

### PR DESCRIPTION
**Pull request by whs**
I want this visualization, so I figured I could write my own

Parties standing are based on https://thestandard.co/thailandelection2562-parties-standpoint/ with some corrections:

- พลังประชารัฐ is not listed. It is marked as supporting NCPO
- ประชาธิปัตย์ does not support Gen. Prayuth to be PM, but is not against พลังประชารัฐ either

Preview

### CODE REVIEW

**Comment by dtinth** [comment]
Let’s release this as 1.2.0

**Comment by dtinth** [comment]
Thanks krub!!

**Comment by rapee** [comment]
Can you also add list of parties supporting each faction? @whs.

By adding `bundle` key, tooltip will show a list of parties. 

```js
// Example
bundledParty = {
  color: "#aaaaaa",
  count: bundledCount,
  id: 999,
  name: "อื่นๆ",
  type: inputParties[0].type,
  bundle: {
    data: bundledPartyList, // Array of party with `count`
    party: bundledPartyList.length, 
    count: bundledCount,
  },
}
```

**Comment by rapee** [comment]
@whs this krub
https://github.com/codeforthailand/election-live/issues/212

**Comment by p16i** [comment]
@whs FYI: you can see your implementation here: https://www.facebook.com/castby9arm/videos/312806899424678/UzpfSTE4MzQ4NDIxOTE6MTAyMTAzMDkwOTMyNDM3NzU/

**Pull request merged**
